apiVersion: v1
kind: Namespace
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/managed-by: kubectl
    environment: development
    project: k8s-fastapi-demo
